### PR TITLE
Fix "Uninitialized string offset -1" warning

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/sebastianbergmann/comparator/issues/118

### CODE REVIEW

**Comment by nuernbergerA** [comment]
can confirm that this fixes it

**Comment by bastienho** [comment]
The patch works for me. 

Thank you for the alacrity

**Comment by xabbuh** [comment]
I can confirm that the patch fixes failures that were caused by 6.2.0 on the Symfony test suite. 👍

**Comment by staabm** [comment]
In https://github.com/phpstan/phpstan-src/pull/3594 I am working on a PHPStan fix, so such errors will be reported by static analysis the next time before we release

**Pull request merged**
