### PR TITLE
Remove common prefixes and suffixes from actual and expected single-line strings

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/sebastianbergmann/comparator/issues/116

### CODE REVIEW

**Comment by staabm** [comment]
//cc @Schrank

**Comment by staabm** [comment]
should be good to go

**Comment by staabm** [comment]
hopefully this will fix this build :)

**Comment by sebastianbergmann** [comment]
AFAICS, the build failed due to GitHub Actions' outage.

**Comment by staabm** [comment]
I saw errors regarding test executed code it should not cover

**Comment by staabm** [comment]
Grreeeeen :-)

**Comment by staabm** [comment]
Grreeeeen :-)

**Comment by staabm** [comment]
you are right. I totally forgot about the suffixes

**Pull request merged**
