### PR TITLE
Update license and copyright in all files

### PR DESCRIPTION
**Pull request by henriquemoody**
https://gist.github.com/henriquemoody/69d1399ba83d389e0974

The code in the gist above, written in PHP, was used to make most of these changes. It is not 100% reliable, that's why I had to check every file.

### CODE REVIEW

**Comment by henriquemoody** [comment]
Just updated: `'s/This file is part of the Comparator./This file is part of the Comparator package./g'`

**Comment by henriquemoody** [comment]
Travis is ok.

**Comment by henriquemoody** [comment]
@sebastianbergmann, is it going to be merged?

**Comment by whatthejeff** [comment]
Looks good to me! Thanks :)

**Pull request merged**
