### PR TITLE
Fix wrong compare when values contain boolean type

### LINKED ISSUE #110: comparing array with bool: true value doesn't throw a ComparisonException
Hello,

I'm using your library to compare array recursively in dev environment.
One of my test was failing randomly while using generated data in it (with faker).
I figured out that the case below doesn't throw an exception, I think it's a weird behaviour so I wanted to notice you, maybe I should not use your library this way, let me know. :) 

```
public function testCompareArrayWeirdBehavior()
{
    $body = [
        'somestr' => true,
    ];
    $toCompareBody = [
        'somestr' => 'some other str',
    ];
    Factory::getInstance()->getComparatorFor($body, $toCompareBody)->assertEquals(
        $body,
        $toCompareBody
    );
}
```

version of the library: `4.0.8`

Thanks for your work anyway ! 👍🏻

### PR DESCRIPTION
**Pull request by kayw-geek**
Fix #110 
Currently, if the expected value is a boolean and the actual value is a string or an integer, they will be incorrectly assumed to be equal. This is because when using a non-strict equality with a boolean, a boolean conversion takes place.

The following behavior does not meet expectations
```
> true == 123
= true

> true == 'bar'
= true
```

### CODE REVIEW

**Comment by kayw-geek** [comment]
Hi @sebastianbergmann, I've submitted a bugfix PR. I believe it could help improve the functionality of the project.

Could you please take some time to review it?

I welcome any feedback you might have and appreciate your time in doing so.

Thanks in advance!

**Comment by sebastianbergmann** [comment]
From the documentation:

> This component provides the functionality to compare PHP values for equality.

This means "according to PHP's rules for equality" (except for special cases such as `DateTime` objects etc.).

```
$ php -v
PHP 8.2.13 (cli) (built: Nov 21 2023 09:55:59) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.2.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.13, Copyright (c), by Zend Technologies
```
```
$ php -a
Interactive shell

php > var_dump(true == 123);
bool(true)
php > var_dump(true == 'bar');
bool(true)
```

**Comment by kayw-geek** [comment]
> From the documentation:
> 
> > This component provides the functionality to compare PHP values for equality.
> 
> This means "according to PHP's rules for equality" (except for special cases such as `DateTime` objects etc.).
> 
> ```
> $ php -v
> PHP 8.2.13 (cli) (built: Nov 21 2023 09:55:59) (NTS gcc x86_64)
> Copyright (c) The PHP Group
> Zend Engine v4.2.13, Copyright (c) Zend Technologies
>     with Zend OPcache v8.2.13, Copyright (c), by Zend Technologies
> ```
> 
> ```
> $ php -a
> Interactive shell
> 
> php > var_dump(true == 123);
> bool(true)
> php > var_dump(true == 'bar');
> bool(true)
> ```

Your statement contradicts the actual behavior in the code. In 'assertEqualsSucceedsProvider()' `ScalarComparatorTest`, you consider 'string' and 'STRING' to be equal, but in PHP they are not equal.

**Comment by kayw-geek** [comment]
I believe more people want the comparison of Boolean values to become more normal.

**Comment by sebastianbergmann** [comment]
> Your statement contradicts the actual behavior in the code. In 'assertEqualsSucceedsProvider()' ScalarComparatorTest, you consider 'string' and 'STRING' to be equal, but in PHP they are not equal.

You did not look closely enough at the test you mention: 'string' is considered to be equal to 'STRING' if and only if capitalisation (casing) is ignored.

**Comment by kayw-geek** [comment]
> > Your statement contradicts the actual behavior in the code. In 'assertEqualsSucceedsProvider()' ScalarComparatorTest, you consider 'string' and 'STRING' to be equal, but in PHP they are not equal.
> 
> You did not look closely enough at the test you mention: 'string' is considered to be equal to 'STRING' if and only if capitalisation (casing) is ignored.

Sorry, I didn't notice that you can set parameters that ignore case-sensitive.

**Comment by kayw-geek** [comment]
@sebastianbergmann  Should we necessary to add  a `StrictScalarComparator` class  and `assertStrictEquals()` method?

**Comment by sebastianbergmann** [comment]
PHPUnit already has `assertEqualsIgnoringCase()`.

**Comment by kayw-geek** [comment]
> PHPUnit already has `assertEqualsIgnoringCase()`.

Thanks, but the can not resolve likely `'bar' == true` case, or should I created a custom comparator?

**Pull request closed without merging**
